/opt/hostedtoolcache/node/24.8.0/x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22051
    throw new Error(
          ^

Error: Error when performing the request to https://repo.yarnpkg.com/tags; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at fetch (/opt/hostedtoolcache/node/24.8.0/x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22051:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchAsJson (/opt/hostedtoolcache/node/24.8.0/x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22065:20)
    ... 3 lines matching cause stack trace ...
    at async Object.runMain (/opt/hostedtoolcache/node/24.8.0/x64/lib/node_modules/corepack/dist/lib/corepack.cjs:23660:7) {
  [cause]: TypeError: fetch failed
      at node:internal/deps/undici/undici:15445:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async fetch (/opt/hostedtoolcache/node/24.8.0/x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22045:16)
      at async fetchAsJson (/opt/hostedtoolcache/node/24.8.0/x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22065:20)
      at async fetchAvailableTags2 (/opt/hostedtoolcache/node/24.8.0/x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22135:20)
      at async Engine.resolveDescriptor (/opt/hostedtoolcache/node/24.8.0/x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22985:20)
      at async Engine.executePackageManagerRequest (/opt/hostedtoolcache/node/24.8.0/x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22959:22)
      at async Object.runMain (/opt/hostedtoolcache/node/24.8.0/x64/lib/node_modules/corepack/dist/lib/corepack.cjs:23660:7) {
    [cause]: AggregateError [ETIMEDOUT]: 
        at internalConnectMultiple (node:net:1134:18)
        at internalConnectMultiple (node:net:1210:5)
        at Timeout.internalConnectMultipleTimeout (node:net:1742:5)
        at listOnTimeout (node:internal/timers:610:11)
        at process.processTimers (node:internal/timers:543:7) {
      code: 'ETIMEDOUT',
      [errors]: [
        Error: connect ETIMEDOUT 104.16.169.120:443
            at createConnectionError (node:net:1678:14)
            at Timeout.internalConnectMultipleTimeout (node:net:1737:38)
            at listOnTimeout (node:internal/timers:610:11)
            at process.processTimers (node:internal/timers:543:7) {
          errno: -110,
          code: 'ETIMEDOUT',
          syscall: 'connect',
          address: '104.16.169.120',
          port: 443
        },
        Error: connect ENETUNREACH 2606:4700::6810:a878:443 - Local (:::0)
            at internalConnectMultiple (node:net:1206:16)
            at Timeout.internalConnectMultipleTimeout (node:net:1742:5)
            at listOnTimeout (node:internal/timers:610:11)
            at process.processTimers (node:internal/timers:543:7) {
          errno: -101,
          code: 'ENETUNREACH',
          syscall: 'connect',
          address: '2606:4700::6810:a878',
          port: 443
        },
        Error: connect ETIMEDOUT 104.16.168.120:443
            at createConnectionError (node:net:1678:14)
            at Timeout.internalConnectMultipleTimeout (node:net:1737:38)
            at listOnTimeout (node:internal/timers:610:11)
            at process.processTimers (node:internal/timers:543:7) {
          errno: -110,
          code: 'ETIMEDOUT',
          syscall: 'connect',
          address: '104.16.168.120',
          port: 443
        },
        Error: connect ENETUNREACH 2606:4700::6810:a978:443 - Local (:::0)
            at internalConnectMultiple (node:net:1206:16)
            at Timeout.internalConnectMultipleTimeout (node:net:1742:5)
            at listOnTimeout (node:internal/timers:610:11)
            at process.processTimers (node:internal/timers:543:7) {
          errno: -101,
          code: 'ENETUNREACH',
          syscall: 'connect',
          address: '2606:4700::6810:a978',
          port: 443
        }
      ]
    }
  }
}

Node.js v24.8.0
